VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsSploit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public retOffset As String ' return offset in hex
Public shellcode As String ' shellcode in hex
Public evilPacket As String ' our final packet is stored here
Public bufferLen As Integer ' the length we have to work with
Public expName As String    ' used only for human reading purposes


Private Sub Class_Initialize()
    Debug.Print "New exploit initialized!"
End Sub

